<Project>
    <ItemGroup Condition="'$(MSBuildProjectName)' != 'PANiXiDA.Core.Infrastructure.Messaging.Wolverine.Generators'">
        <ProjectReference Include="$(MSBuildThisFileDirectory)src/PANiXiDA.Core.Infrastructure.Messaging.Wolverine.Generators/PANiXiDA.Core.Infrastructure.Messaging.Wolverine.Generators.csproj"
                          OutputItemType="Analyzer" ReferenceOutputAssembly="false" PrivateAssets="all"
                          GlobalPropertiesToRemove="PublishAot;RuntimeIdentifier;SelfContained;PublishTrimmed;IsAotCompatible;EnableAotAnalyzer;EnableTrimAnalyzer">
            <ReferenceOutputAssembly Condition="'$(MSBuildProjectName)' == 'PANiXiDA.Core.Infrastructure.Messaging.Wolverine.UnitTests'">true</ReferenceOutputAssembly>
        </ProjectReference>
    </ItemGroup>
    <PropertyGroup Condition="'$(IsPackable)' == 'true'">
        <Authors>PANiXiDA</Authors>
        <Company>PANiXiDA</Company>
        <RepositoryType>git</RepositoryType>

        <PublishRepositoryUrl>true</PublishRepositoryUrl>
        <EmbedUntrackedSources>true</EmbedUntrackedSources>

        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>

        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
        <PackageIcon>icon.png</PackageIcon>
    </PropertyGroup>

    <ItemGroup Condition="'$(IsPackable)' == 'true'">
        <None Include="$(MSBuildThisFileDirectory)README.md"
              Pack="true"
              PackagePath="\"
              Visible="false" />

        <None Include="$(MSBuildThisFileDirectory)icon.png"
              Pack="true"
              PackagePath="\"
              Visible="false" />
    </ItemGroup>
</Project>
