using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace PANiXiDA.Core.Infrastructure.Messaging.Wolverine.Generators.Validation;

internal sealed class ValidatorRegistrationSourceBuilder
{
    private readonly StringBuilder source = new("""
        // <auto-generated />
        #nullable enable
        #pragma warning disable CA2255

        file static class GeneratedWolverineValidators
        {
            [global::System.Runtime.CompilerServices.ModuleInitializer]
            internal static void Initialize()
            {
                global::PANiXiDA.Core.Infrastructure.Messaging.Wolverine.Generation.ValidatorRegistry.RegisterAssemblies(

        """);

    internal ValidatorRegistrationSourceBuilder(IAssemblySymbol[] assemblies)
    {
        for (var index = 0; index < assemblies.Length; index++)
        {
            source.Append("            ")
                .Append(Literal(assemblies[index].Identity.ToString()))
                .Append(index == assemblies.Length - 1 ? ");\n" : ",\n");
        }
    }

    internal void Add(
        INamedTypeSymbol type,
        INamedTypeSymbol contract,
        bool accessible)
    {
        var typeName = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        source.Append("        global::PANiXiDA.Core.Infrastructure.Messaging.Wolverine.Generation.")
            .Append("ValidatorRegistry.Register(\n")
            .Append("            ")
            .Append(Literal(type.ContainingAssembly.Identity.ToString()))
            .Append(",\n")
            .Append("            ")
            .Append(Literal(typeName))
            .Append(",\n");

        if (!accessible)
        {
            source.Append("            null);\n");
            return;
        }

        source.Append("            static services =>\n            {\n")
            .Append("                global::Microsoft.Extensions.DependencyInjection.Extensions.")
            .Append("ServiceCollectionDescriptorExtensions.TryAddEnumerable(\n")
            .Append("                    services,\n")
            .Append("                    global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Scoped<\n")
            .Append("                        ")
            .Append(contract.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat))
            .Append(",\n")
            .Append("                        ")
            .Append(typeName)
            .Append(">());\n")
            .Append("                global::Microsoft.Extensions.DependencyInjection.Extensions.")
            .Append("ServiceCollectionDescriptorExtensions.TryAdd(\n")
            .Append("                    services,\n")
            .Append("                    global::Microsoft.Extensions.DependencyInjection.ServiceDescriptor.Scoped<\n")
            .Append("                        ")
            .Append(typeName)
            .Append(",\n")
            .Append("                        ")
            .Append(typeName)
            .Append(">());\n")
            .Append("            });\n");
    }

    internal string Build()
    {
        return source.Append("    }\n}\n").ToString();
    }

    private static string Literal(string value)
    {
        return SymbolDisplay.FormatLiteral(value, quote: true);
    }
}
